FROM python:3.10 as base

WORKDIR /app
ADD pyproject.toml .
RUN pip install . && rm pyproject.toml
ENV PYTHONPATH=/app
ADD pr_agent pr_agent

ENTRYPOINT ["python", "/app/pr_agent/servers/github_action_runner.py"]
